site_name: dagster-pyiceberg

# Repository
repo_name: JasperHG90/dagster-pyiceberg
repo_url: https://github.com/JasperHG90/dagster-pyiceberg
edit_uri: ""

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Features: features.md
  - Reference: reference.md
  - Developing: development.md
  #- "Code reference": code_reference.md

theme:
  name: "material"
  logo: assets/dagster-pyiceberg-logo-small.png
  features:
    - content.code.select
    - content.code.copy

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [packages/dagster_pyiceberg]
- include-markdown
