site_name: dagster-pyiceberg
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Reference: reference.md
  - Developing: development.md
  - Examples:
    - Pandas: examples/pandas.md
    - Polars: examples/polars.md

theme:
  name: "material"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings
- include-markdown
