[project]
name = "dagster-pyiceberg"
version = "0.1.0"
description = ""
authors = [
  {name="Jasper Ginn", email="jasperginn@gmail.com"}
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "pyiceberg[pyarrow]>=0.7.1",
    "dagster>=1.8.2",
    "dagit>=1.8.2",
    "pendulum>=3.0.0",
]

[tool.uv]
dev-dependencies = [
    "pre-commit>=3.8.0",
    "ipykernel>=6.29.5",
    "pytest>=8.3.2",
    "pandas>=2.2.2",
    "pyright>=1.1.385",
]

[tool.uv.sources]
pyiceberg = { git = "https://github.com/apache/iceberg-python", rev = "09ec814" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
exclude = '''
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.venv
    | _build
    | build
    | dist
    | .notebooks
    | .nox
  )
)
'''

[tool.isort]
profile = "black"
extend_skip = [".notebooks", ".nox", ".venv"]

[tool.mypy]
exclude = "^.notebooks/"
ignore_missing_imports = true

[tool.bandit]
skips = ['B101']

[tool.ruff]
lint.ignore = ["E501"]
extend-exclude = [
  "__pycache__",
  "docs",
  "site",
  ".nox",
  ".notebooks"
]

[tool.pytest.ini_options]
cache_dir = "/home/vscode/workspace/.cache/pytest"

[tool.pyright]
include = ["src"]
pythonVersion = "3.11"
venvPath = "."
venv = ".venv"
