[project]
name = "dagster-pyiceberg-pandas"
version = "0.0.0"
description = "Package for storing Pandas DataFrames in PyIceberg tables."
authors = [
  {name="Jasper Ginn", email="jasperginn@gmail.com"}
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "dagster-pyiceberg",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
