name: "Pyright type checks"
description: "Template that runs pre-commit hooks"

inputs:
    python_version:
        description: "Python version to use."
        required: false
        default: "3.11"
    uv_version:
        description: "uv version to use."
        required: true
    pyright_version:
        description: "Pre-commit version to use."
        required: false
        default: "3.1.1"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        uv-version: ${{ inputs.uv_version }}
    - name: install dependencies
      run: |
        uv sync --all-extras
      shell: bash
    - name: Run pyright
      run: |
        uv run pyright
      shell: bash
