[project]
name = "dagster-pyiceberg"
version = "0.0.0"
description = "Package for PyIceberg-specific Dagster framework op and resource components."
authors = [
  {name="Jasper Ginn", email="jasperginn@gmail.com"}
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "pyiceberg[pyarrow]>=0.7.1",
    "dagster>=1.8.2",
    "dagit>=1.8.2",
    "pendulum>=3.0.0",
    "tenacity>=8.5.0",
]

[tool.uv.sources]
pyiceberg = { git = "https://github.com/apache/iceberg-python", rev = "09ec814" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
