[project]
name = "dagster-pyiceberg"
version = "0.0.0"
description = "Package for PyIceberg-specific Dagster framework op and resource components."
authors = [
  {name="Jasper Ginn", email="jasperginn@gmail.com"}
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "dagster>=1.8.2",
    "pendulum>=3.0.0",
    "pyiceberg[pyarrow]==0.8.0rc1",
    "tenacity>=8.5.0",
]
maintainers = [
  {name="Jasper Ginn", email="jasperginn@gmail.com"}
]
license = {file = "LICENSE.txt"}
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://jasperhg90.github.io/dagster-pyiceberg/"
Documentation = "https://jasperhg90.github.io/dagster-pyiceberg/"
Repository = "https://github.com/JasperHG90/dagster-pyiceberg"
"Bug Tracker" = "https://github.com/JasperHG90/dagster-pyiceberg/issues"
