name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: 'Pre-commit checks'
        uses: ./.github/workflows/templates/checks
        with:
          python_version: "3.11"
          pre_commit_version: "4.0.1"
          directory: "."
      - name: 'Pyright type checks'
        uses: ./.github/workflows/templates/pyright_type_checks
        with:
          uv_version: "0.4.27"
          python_version: "3.11"
          pyright_version: "1.1.385"
  tests:
    runs-on: ubuntu-latest
    needs: checks
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: 'tests'
        uses: ./.github/workflows/templates/tests
        with:
          uv_version: "0.4.27"
          python_version: ${{ matrix.python_version }}
          directory: "tests"
