name: 'Release'

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: read

concurrency:
  # This prevents concurrency in building/deploying an environment.
  group: release
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build python packages
        uses: ./.github/workflows/templates/release/build
        with:
          python_version: '3.11'
          uv_version: '0.4.27'
          path_to_packages: './packages'
